spring.application.name=lab8-673380596-5-sec4

spring.datasource.url=jdbc:postgresql://localhost:5432/productshop_db
spring.datasource.username=postgres
spring.datasource.password=4771169

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate=org.hibernate.dialect.PostgreSQLDialect